"""EMBER direction-masked LoRA SFT data builder (cold-item / cold-user).

v3 implements user-requested features:

  1. Similarity-filtered top-L history (paper §4.2.2 Eq.8):
       - For each (user, target_video) pair: pick top-L of user's past clicked
         videos most similar (cosine over text-embedding-3-small) to the target.
       - For each (target_user, video) pair: pick top-L of video's past clickers
         most similar to the target user.

  2. Symmetric, watch-time-aware context blocks:
       - USER block lists user's past clicks with their watch_time + long_view
         (top-L by similarity to target video).
       - VIDEO block lists video's past clickers with their watch_time +
         long_view + a snippet of viewer demographic (top-L by similarity to
         target user).

  3. Two output formats per dataset:
       - no_reasoning  : assistant = JSON  {click, long_view, watch_time_seconds}
       - with_reasoning: assistant = JSON  {reasoning, click, long_view, watch_time_seconds}
         The `reasoning` string is generated by gpt-4o-mini as a teacher (one
         async pass after the base dataset is built).

  4. Three focus types:
       - cold_item : prompts mask out the VIDEO behavior summary + clicker list
                      (mimicking the inference scenario where target item is cold).
       - cold_user : prompts mask out the USER behavior summary + user history
                      (mimicking cold-user inference).
       - both      : full context (combined / universal LoRA).

Total outputs: 3 focus × 2 reasoning = 6 dataset variants
   data/lora_v3/{focus}_{reasoning}/{train,val}.jsonl
"""
from __future__ import annotations
import argparse, asyncio, json, os, sys, time
from collections import Counter
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd


# ─── System prompts ──────────────────────────────────────────────
SYSTEM_PROMPT_NO_REASONING = (
    "You are a short-video recommender simulator for KuaiRand. You are given a "
    "USER (demographic profile + behavior summary + click history with watch times) "
    "AND a VIDEO (description + behavior summary + past clickers with watch times). "
    "Predict three things in JSON: \"click\" (0 or 1), \"long_view\" (0 or 1 — if "
    "clicked, watched >5 seconds), \"watch_time_seconds\" (integer 0-60). "
    "Output ONLY the JSON object, no prose."
)

SYSTEM_PROMPT_WITH_REASONING = (
    "You are a short-video recommender simulator for KuaiRand. You are given a "
    "USER (demographic profile + behavior summary + click history with watch times) "
    "AND a VIDEO (description + behavior summary + past clickers with watch times). "
    "First reason briefly about user-video fit. Then output JSON with FOUR keys: "
    "\"reasoning\" (1-2 sentence explanation), \"click\" (0/1), \"long_view\" (0/1), "
    "\"watch_time_seconds\" (integer 0-60). Output ONLY the JSON object."
)


# ─── Helpers ─────────────────────────────────────────────────────
def _cosine_sim_matrix(query: np.ndarray, pool: np.ndarray) -> np.ndarray:
    """query: (D,), pool: (N, D) -> (N,) cosines."""
    qn = query / (np.linalg.norm(query) + 1e-8)
    pn = pool / (np.linalg.norm(pool, axis=1, keepdims=True) + 1e-8)
    return pn @ qn


def filter_user_history_by_sim(
    history: List[Tuple[int, int, int, int]],  # (time_ms, video_id, wt_s, lv)
    target_video_emb: np.ndarray,
    video_text_emb_lookup: np.ndarray,
    top_l: int,
) -> List[Tuple[int, int, int, int]]:
    if not history:
        return []
    if len(history) <= top_l:
        return history
    vids = np.array([h[1] for h in history])
    pool = video_text_emb_lookup[vids]
    sims = _cosine_sim_matrix(target_video_emb, pool)
    top_idx = np.argpartition(-sims, top_l - 1)[:top_l]
    return [history[i] for i in top_idx]


def filter_video_clickers_by_sim(
    clickers: List[Tuple[int, int, int, int]],  # (time_ms, user_id, wt_s, lv)
    target_user_emb: np.ndarray,
    user_text_emb_lookup: np.ndarray,
    top_l: int,
) -> List[Tuple[int, int, int, int]]:
    if not clickers:
        return []
    if len(clickers) <= top_l:
        return clickers
    uids = np.array([c[1] for c in clickers])
    pool = user_text_emb_lookup[uids]
    sims = _cosine_sim_matrix(target_user_emb, pool)
    top_idx = np.argpartition(-sims, top_l - 1)[:top_l]
    return [clickers[i] for i in top_idx]


# ─── Behavior summary helpers (reused from v2) ───────────────────
def build_user_behavior_summary(clicks_df, video_categories, top_n=3, wt_max=60):
    n = len(clicks_df)
    if n == 0:
        return "No prior click history yet."
    cats = []
    for vid in clicks_df["video_id"].tolist():
        c = video_categories.get(int(vid), "")
        if isinstance(c, str) and c: cats.append(c.split(" > ")[0])
    top_cats = [c for c, _ in Counter(cats).most_common(top_n)]
    cat_str = ", ".join(top_cats) if top_cats else "various"
    wt = (clicks_df["play_time_ms"].clip(0) / 1000.0).clip(0, wt_max)
    return (f"They have clicked {n} videos so far. Preferred categories: "
            f"{cat_str}. Average watch time per clicked video: {wt.mean():.0f}s; "
            f"long-view rate: {clicks_df['long_view'].mean()*100:.0f}%.")


def build_video_behavior_summary(impr_df, user_feat_lookup, top_n=2, wt_max=60):
    n_impr = len(impr_df)
    if n_impr == 0:
        return "This video has never been shown in training."
    clicks = impr_df[impr_df["is_click"] == 1]
    n_clicks = len(clicks)
    ctr = n_clicks / max(n_impr, 1) * 100
    if n_clicks == 0:
        return (f"Shown {n_impr} times, zero clicks (CTR 0%) — cold/unpopular.")
    wt = (clicks["play_time_ms"].clip(0) / 1000.0).clip(0, wt_max)
    activity_counts = Counter(); role_counts = Counter()
    for uid in clicks["user_id"].unique():
        info = user_feat_lookup.get(int(uid))
        if not info: continue
        activity_counts[str(info.get("user_active_degree", ""))] += 1
        roles = []
        if int(info.get("is_live_streamer", 0) or 0): roles.append("streamer")
        if int(info.get("is_video_author", 0) or 0):  roles.append("author")
        if roles:
            role_counts[" & ".join(sorted(roles))] += 1
    top_act = [a for a, _ in activity_counts.most_common(top_n) if a]
    top_role = [r for r, _ in role_counts.most_common(top_n) if r]
    extras = []
    if top_act: extras.append(f"clickers mostly {', '.join(top_act)} users")
    if top_role: extras.append(f"often {top_role[0]}")
    extras_str = " — " + "; ".join(extras) if extras else ""
    return (f"Shown {n_impr} times, {n_clicks} clicks (CTR {ctr:.1f}%); "
            f"average watch {wt.mean():.0f}s, long-view rate "
            f"{clicks['long_view'].mean()*100:.0f}%{extras_str}.")


def short_user_snippet(uid, user_features_lookup) -> str:
    """One-line snippet of a viewer demographic for the video-side context."""
    info = user_features_lookup.get(int(uid))
    if not info: return "anonymous user"
    parts = []
    act = str(info.get("user_active_degree", "")).strip()
    if act and act != "nan":
        parts.append(act.replace("_", " "))
    roles = []
    if int(info.get("is_live_streamer", 0) or 0): roles.append("streamer")
    if int(info.get("is_video_author", 0) or 0):  roles.append("author")
    if roles: parts.append("/".join(roles))
    fan_range = str(info.get("fans_user_num_range", "")).strip()
    if fan_range and fan_range != "nan":
        parts.append(f"fans:{fan_range}")
    return ", ".join(parts) or "anonymous user"


# ─── Prompt builder ──────────────────────────────────────────────
def build_history_lines(history_items, video_views_lookup, label="watched"):
    """history_items: list of (time_ms, video_id, wt_s, lv) → numbered lines."""
    lines = []
    for i, (_, vid, wt_s, lv) in enumerate(history_items):
        v_text = video_views_lookup.get(int(vid), "(no description)")[:140]
        lv_tag = "long_view" if lv else "short"
        lines.append(f"{i+1}. {v_text} — {label} {wt_s}s ({lv_tag})")
    return "\n".join(lines) if lines else "(none)"


def build_video_clicker_lines(clicker_items, user_features_lookup, label="watched"):
    """clicker_items: list of (time_ms, user_id, wt_s, lv) → numbered lines."""
    lines = []
    for i, (_, uid, wt_s, lv) in enumerate(clicker_items):
        snippet = short_user_snippet(uid, user_features_lookup)
        lv_tag = "long_view" if lv else "short"
        lines.append(f"{i+1}. [{snippet}] — {label} {wt_s}s ({lv_tag})")
    return "\n".join(lines) if lines else "(none)"


def build_user_prompt_full(
    user_profile, user_behavior, user_hist_lines,
    video_text, video_cat, video_cap, video_behavior, video_clicker_lines,
    focus: str,
    reasoning_request: bool,
) -> str:
    """`focus` controls which behavior blocks are masked out to simulate cold scenarios."""
    user_behavior_block = user_behavior if focus != "cold_user" else "(insufficient history for behavior summary — this user is cold)"
    user_hist_block     = user_hist_lines if focus != "cold_user" else "(no/sparse prior clicks — this user is cold)"
    video_behavior_block= video_behavior if focus != "cold_item" else "(insufficient history for behavior summary — this video is cold)"
    video_clicker_block = video_clicker_lines if focus != "cold_item" else "(no/sparse prior clickers — this video is cold)"

    tgt = video_text
    if isinstance(video_cat, str) and video_cat: tgt = f"[{video_cat}] {tgt}"
    if isinstance(video_cap, str) and video_cap: tgt = f"{tgt} — caption hints: {video_cap[:80]}"

    task_block = (
        "First, reason briefly (1-2 sentences) about user-video fit using the "
        "above context. Then return JSON with FOUR keys: "
        "{\"reasoning\": str, \"click\": int, \"long_view\": int, \"watch_time_seconds\": int}"
        if reasoning_request else
        "Return JSON: {\"click\": int, \"long_view\": int, \"watch_time_seconds\": int}"
    )

    return (
        f"### USER — DEMOGRAPHIC PROFILE\n{user_profile}\n\n"
        f"### USER — BEHAVIOR SUMMARY\n{user_behavior_block}\n\n"
        f"### USER — CLICK HISTORY MOST SIMILAR TO TARGET (with watch_time)\n{user_hist_block}\n\n"
        f"### VIDEO — DESCRIPTION\n{tgt}\n\n"
        f"### VIDEO — BEHAVIOR SUMMARY\n{video_behavior_block}\n\n"
        f"### VIDEO — PAST CLICKERS MOST SIMILAR TO USER (with watch_time)\n{video_clicker_block}\n\n"
        f"### TASK\n{task_block}"
    )


def to_chatml(prompt: str, label_obj: dict, with_reasoning: bool) -> Dict:
    system = SYSTEM_PROMPT_WITH_REASONING if with_reasoning else SYSTEM_PROMPT_NO_REASONING
    return {
        "messages": [
            {"role": "system",    "content": system},
            {"role": "user",      "content": prompt},
            {"role": "assistant", "content": json.dumps(label_obj, ensure_ascii=False)},
        ]
    }


# ─── Reasoning generation (async, gpt-4o-mini) ───────────────────
def _extract_reasoning_text(raw: str) -> str:
    """Robustly extract reasoning text from LLM output that may include JSON,
    code fences, prefixed prose, or TRUNCATED JSON. Returns a single clean
    reasoning sentence."""
    import re
    raw = (raw or "").strip()
    if not raw:
        return ""
    # Strip markdown fences
    if raw.startswith("```"):
        raw = re.sub(r"^```[^\n]*\n?", "", raw)
        raw = re.sub(r"\n?```$", "", raw)
        raw = raw.strip()
    # 1) Try to extract complete JSON's 'reasoning' field
    m_json = re.search(r"\{[\s\S]*\}", raw)  # greedy this time
    if m_json:
        try:
            obj = json.loads(m_json.group(0))
            if isinstance(obj, dict) and "reasoning" in obj:
                inner = str(obj["reasoning"]).strip()
                if inner:
                    return inner
        except Exception:
            pass
        # 2) Regex on quoted reasoning field (even in malformed JSON)
        m_inner = re.search(r'"reasoning"\s*:\s*"((?:[^"\\]|\\.)*)"', raw)
        if m_inner:
            val = m_inner.group(1).strip()
            if val:
                return val
    # 3) Detect truncated JSON: any `{"...` marker → take prose BEFORE it
    m_brace = re.search(r"\{", raw)
    if m_brace:
        before = raw[:m_brace.start()].strip()
        if before:
            raw = before
    # 4) Strip "Reasoning:" labels etc.
    raw = re.sub(r"^(reasoning|reason|explanation|answer)\s*[:\-]\s*", "", raw,
                  flags=re.IGNORECASE)
    raw = raw.strip()
    # 5) Truncate to first 2 sentences max (safety against runaway prose)
    sents = re.split(r"(?<=[.!?])\s+", raw)
    if len(sents) > 2:
        raw = " ".join(sents[:2])
    return raw.strip()


async def gen_reasoning_for_record(client, sem, model, user_msg: str, label_obj: dict,
                                     max_retries=3) -> str:
    """Ask gpt-4o-mini to produce a 1-2 sentence reasoning consistent with the
    ground-truth label, given the user prompt. Robust to LLM output formatting."""
    sys_msg = (
        "You will see a recommendation context and the GROUND-TRUTH outcome "
        "(click / long_view / watch_time_seconds). Reply with exactly ONE plain "
        "English sentence (max 30 words) that explains WHY this outcome is "
        "plausible from the context. Do NOT output JSON. Do NOT output markdown. "
        "Do NOT prefix with 'Reasoning:' or any label. Just one sentence ending "
        "with a period."
    )
    ground = (f"GROUND TRUTH: click={label_obj['click']}, "
              f"long_view={label_obj['long_view']}, "
              f"watch_time_seconds={label_obj['watch_time_seconds']}.")
    full_user = f"{user_msg}\n\n{ground}"
    async with sem:
        for attempt in range(max_retries):
            try:
                resp = await client.chat.completions.create(
                    model=model,
                    messages=[{"role": "system", "content": sys_msg},
                              {"role": "user", "content": full_user}],
                    temperature=0.2, timeout=30.0,
                    max_completion_tokens=200,
                )
                raw = (resp.choices[0].message.content or "").strip()
                return _extract_reasoning_text(raw)
            except Exception as e:
                if attempt == max_retries - 1:
                    return "(reasoning unavailable)"
                await asyncio.sleep(1.5 * (attempt + 1))


async def add_reasoning_pass(records, model="gpt-4o-mini", concurrency=200):
    """records: list of {prompt, label_obj}. Adds 'reasoning' field in-place."""
    from openai import AsyncOpenAI
    client = AsyncOpenAI()
    sem = asyncio.Semaphore(concurrency)
    print(f"\n  Generating reasoning for {len(records):,} records "
          f"(model={model}, concurrency={concurrency})…", flush=True)
    t0 = time.time(); done = [0]

    async def one(rec):
        rec["reasoning"] = await gen_reasoning_for_record(client, sem, model,
                                                           rec["prompt"], rec["label_obj"])
        done[0] += 1
        if done[0] % 500 == 0:
            print(f"    {done[0]:,}/{len(records):,} done ({time.time()-t0:.0f}s)",
                  flush=True)

    await asyncio.gather(*(one(r) for r in records))
    print(f"  done in {time.time()-t0:.0f}s", flush=True)


# ─── Orchestrator ─────────────────────────────────────────────
def main():
    p = argparse.ArgumentParser()
    p.add_argument("--log_csvs", nargs="+",
                    default=["./data/kuairand_pure/KuaiRand-Pure/data/log_random_4_22_to_5_08_pure.csv"])
    p.add_argument("--video_meta_csv", default="./data/kuairand_pure/enriched_video_metadata_pure.csv")
    p.add_argument("--user_profile_csv", default="./llm_cold_item/data/user_profile_text.csv")
    p.add_argument("--user_features_csv",
                    default="./data/kuairand_pure/KuaiRand-Pure/data/user_features_pure.csv")
    p.add_argument("--video_text_emb_npz", default="./llm_cold_item/data/text_emb_video_pure.npz")
    p.add_argument("--user_text_emb_npz",  default="./llm_cold_item/data/text_emb_user_pure.npz")
    p.add_argument("--out_dir", default="./llm_cold_item/data/lora_v3")
    p.add_argument("--n_train", type=int, default=8000)
    p.add_argument("--n_val", type=int, default=1000)
    p.add_argument("--top_l", type=int, default=5)
    p.add_argument("--train_ratio", type=float, default=0.8)
    p.add_argument("--wt_max", type=int, default=60)
    p.add_argument("--gen_reasoning", action="store_true",
                    help="If set, also build the with_reasoning variants via gpt-4o-mini.")
    p.add_argument("--reasoning_model", default="gpt-4o-mini")
    p.add_argument("--reasoning_concurrency", type=int, default=200)
    p.add_argument("--focus", choices=["cold_item", "cold_user", "both", "ALL"], default="ALL")
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    rng = np.random.default_rng(args.seed)

    print(f"[A] Load + restrict log to train period", flush=True)
    frames = [pd.read_csv(c, usecols=["user_id", "video_id", "time_ms",
                                        "is_click", "long_view", "play_time_ms"],
                            dtype={"user_id": np.int64, "video_id": np.int64,
                                   "time_ms": np.int64, "is_click": np.int64,
                                   "long_view": np.int64, "play_time_ms": np.int64})
              for c in args.log_csvs]
    log = pd.concat(frames, ignore_index=True).sort_values("time_ms").reset_index(drop=True)
    train_log = log.iloc[:int(len(log) * args.train_ratio)]
    print(f"  total {len(log):,}, train_period {len(train_log):,}", flush=True)
    pos_log = train_log[train_log["is_click"] == 1].copy()

    print(f"\n[B] Load text resources + embeddings", flush=True)
    vm = pd.read_csv(args.video_meta_csv)
    video_views = dict(zip(vm["video_id"].astype(int), vm["semantic_view_en"].astype(str)))
    video_cats  = dict(zip(vm["video_id"].astype(int), vm["category_en"].astype(str)))
    video_caps  = dict(zip(vm["video_id"].astype(int), vm["caption_en"].astype(str)))
    up = pd.read_csv(args.user_profile_csv)
    user_profiles = dict(zip(up["user_id"].astype(int), up["profile_en"].astype(str)))
    uf = pd.read_csv(args.user_features_csv)
    user_feat_lookup = {int(r["user_id"]): r.to_dict() for _, r in uf.iterrows()}

    vte = np.load(args.video_text_emb_npz)
    v_emb = vte["text_emb"]; v_ids = vte["ids"]
    v_text_arr = np.zeros((int(v_ids.max()) + 1, v_emb.shape[1]), dtype=np.float32)
    v_text_arr[v_ids] = v_emb
    ute = np.load(args.user_text_emb_npz)
    u_emb = ute["text_emb"]; u_ids = ute["ids"]
    u_text_arr = np.zeros((int(u_ids.max()) + 1, u_emb.shape[1]), dtype=np.float32)
    u_text_arr[u_ids] = u_emb

    print(f"\n[C] Build per-user click history with watch_time", flush=True)
    user_history: Dict[int, List[Tuple[int, int, int, int]]] = {}
    user_clicks_set: Dict[int, set] = {}
    for uid, grp in pos_log.groupby("user_id"):
        items = []
        for _, r in grp.sort_values("time_ms").iterrows():
            wt = max(0, min(args.wt_max, int(r["play_time_ms"]) // 1000))
            items.append((int(r["time_ms"]), int(r["video_id"]), wt, int(r["long_view"])))
        user_history[int(uid)] = items
        user_clicks_set[int(uid)] = set(v for _, v, _, _ in items)
    print(f"  users with click history: {len(user_history):,}", flush=True)

    print(f"\n[D] Build per-video clicker list with watch_time", flush=True)
    video_clickers: Dict[int, List[Tuple[int, int, int, int]]] = {}
    for vid, grp in pos_log.groupby("video_id"):
        items = []
        for _, r in grp.sort_values("time_ms").iterrows():
            wt = max(0, min(args.wt_max, int(r["play_time_ms"]) // 1000))
            items.append((int(r["time_ms"]), int(r["user_id"]), wt, int(r["long_view"])))
        video_clickers[int(vid)] = items
    print(f"  videos with clickers: {len(video_clickers):,}", flush=True)

    print(f"\n[E] Compute per-user + per-video behavior summaries", flush=True)
    user_summaries = {int(uid): build_user_behavior_summary(grp, video_cats)
                       for uid, grp in pos_log.groupby("user_id")}
    video_summaries = {int(vid): build_video_behavior_summary(grp, user_feat_lookup)
                        for vid, grp in train_log.groupby("video_id")}
    pd.DataFrame(sorted(user_summaries.items()), columns=["user_id", "behavior_summary_en"]) \
        .to_csv(os.path.join(args.out_dir, "user_behavior_summary.csv"), index=False)
    pd.DataFrame(sorted(video_summaries.items()), columns=["video_id", "behavior_summary_en"]) \
        .to_csv(os.path.join(args.out_dir, "video_behavior_summary.csv"), index=False)
    print(f"  user summaries: {len(user_summaries):,}, video: {len(video_summaries):,}",
          flush=True)

    all_video_ids = np.array(list(video_views.keys()), dtype=np.int64)
    users_with_hist = list(user_history.keys())

    print(f"\n[F] Build samples (positives + unobserved)", flush=True)
    pos_arr = pos_log[["user_id", "video_id", "time_ms", "long_view", "play_time_ms"]].values

    def make_one_sample(uid: int, vid: int, label: dict, focus: str, with_reasoning: bool):
        user_prof = user_profiles.get(uid, "")
        user_beh  = user_summaries.get(uid, "No prior click history yet.")
        v_text    = video_views.get(vid, "")
        v_cat     = video_cats.get(vid, "")
        v_cap     = video_caps.get(vid, "")
        v_beh     = video_summaries.get(vid, "")
        if not user_prof or not v_text:
            return None
        # User history block (similarity-filtered, exclude target video)
        hist = [h for h in user_history.get(uid, []) if h[1] != vid]
        if vid < len(v_text_arr):
            hist_filt = filter_user_history_by_sim(hist, v_text_arr[vid], v_text_arr, args.top_l)
        else:
            hist_filt = hist[-args.top_l:]
        hist_lines = build_history_lines(hist_filt, video_views)
        # Video clickers block (similarity-filtered, exclude target user)
        clk = [c for c in video_clickers.get(vid, []) if c[1] != uid]
        if uid < len(u_text_arr):
            clk_filt = filter_video_clickers_by_sim(clk, u_text_arr[uid], u_text_arr, args.top_l)
        else:
            clk_filt = clk[-args.top_l:]
        clk_lines = build_video_clicker_lines(clk_filt, user_feat_lookup)
        prompt = build_user_prompt_full(
            user_prof, user_beh, hist_lines,
            v_text, v_cat, v_cap, v_beh, clk_lines,
            focus=focus, reasoning_request=with_reasoning,
        )
        return {"prompt": prompt, "label_obj": label}

    def sample_positives(n: int, focus: str, with_reasoning: bool):
        order = rng.permutation(len(pos_arr))
        out = []
        for idx in order:
            uid, vid, t, lv, pt_ms = pos_arr[idx]
            uid, vid = int(uid), int(vid)
            wt = max(0, min(args.wt_max, int(pt_ms) // 1000))
            label = {"click": 1, "long_view": int(lv), "watch_time_seconds": int(wt)}
            rec = make_one_sample(uid, vid, label, focus, with_reasoning)
            if rec is not None: out.append(rec)
            if len(out) >= n: break
        return out

    def sample_unobserved(n: int, focus: str, with_reasoning: bool):
        out = []; attempts = 0; max_attempts = n * 8
        while len(out) < n and attempts < max_attempts:
            attempts += 1
            uid = int(rng.choice(users_with_hist))
            vid = int(rng.choice(all_video_ids))
            if vid in user_clicks_set.get(uid, set()):
                continue
            label = {"click": 0, "long_view": 0, "watch_time_seconds": 0}
            rec = make_one_sample(uid, vid, label, focus, with_reasoning)
            if rec is not None: out.append(rec)
        return out

    foci = ["cold_item", "cold_user", "both"] if args.focus == "ALL" else [args.focus]

    for focus in foci:
        focus_dir = os.path.join(args.out_dir, focus)
        os.makedirs(focus_dir, exist_ok=True)
        print(f"\n=== FOCUS: {focus} ===", flush=True)

        # Build no_reasoning train + val
        print(f"  building NO_REASONING train (n={args.n_train})", flush=True)
        train_recs = sample_positives(args.n_train // 2, focus, False) + \
                      sample_unobserved(args.n_train // 2, focus, False)
        rng.shuffle(train_recs)
        print(f"  building NO_REASONING val (n={args.n_val})", flush=True)
        val_recs = sample_positives(args.n_val // 2, focus, False) + \
                    sample_unobserved(args.n_val // 2, focus, False)
        rng.shuffle(val_recs)

        no_dir = os.path.join(focus_dir, "no_reasoning")
        os.makedirs(no_dir, exist_ok=True)
        for split, recs in [("train", train_recs), ("val", val_recs)]:
            path = os.path.join(no_dir, f"{split}.jsonl")
            with open(path, "w", encoding="utf-8") as f:
                for r in recs:
                    f.write(json.dumps(to_chatml(r["prompt"], r["label_obj"], False),
                                        ensure_ascii=False) + "\n")
            print(f"    → {path} ({len(recs):,})", flush=True)

        if args.gen_reasoning:
            print(f"  generating WITH_REASONING variant (LLM teacher)", flush=True)
            train_recs_r = sample_positives(args.n_train // 2, focus, True) + \
                            sample_unobserved(args.n_train // 2, focus, True)
            rng.shuffle(train_recs_r)
            val_recs_r = sample_positives(args.n_val // 2, focus, True) + \
                          sample_unobserved(args.n_val // 2, focus, True)
            rng.shuffle(val_recs_r)
            asyncio.run(add_reasoning_pass(train_recs_r,
                                            args.reasoning_model, args.reasoning_concurrency))
            asyncio.run(add_reasoning_pass(val_recs_r,
                                            args.reasoning_model, args.reasoning_concurrency))
            yes_dir = os.path.join(focus_dir, "with_reasoning")
            os.makedirs(yes_dir, exist_ok=True)
            for split, recs in [("train", train_recs_r), ("val", val_recs_r)]:
                path = os.path.join(yes_dir, f"{split}.jsonl")
                with open(path, "w", encoding="utf-8") as f:
                    for r in recs:
                        label_with_reasoning = {"reasoning": r.get("reasoning", ""), **r["label_obj"]}
                        f.write(json.dumps(to_chatml(r["prompt"], label_with_reasoning, True),
                                            ensure_ascii=False) + "\n")
                print(f"    → {path} ({len(recs):,})", flush=True)

    print(f"\nDONE.", flush=True)


if __name__ == "__main__":
    main()
